require("lukas.options")
require("lukas.keymaps")
require("lukas.plugins")
require("lukas.colorscheme")
require("lukas.cmp")
require("lukas.lsp")
require("lukas.telescope")
require("lukas.treesitter")
require("lukas.terminal")
require("lukas.lualine")
require("lukas.autopairs")
require("lukas.gitsigns")
require("lukas.comment")
require("lukas.todo-comment")
require("lukas.nvim-tree")
require("lukas.dap")

--[[ highligh color in nvim ]]
require("lukas.colorizer")

require("lukas.bufferline")
require("lukas.whichkey")
require("lukas.git-conflict")
